// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "gateway"
		appVersion: "1.0.0"
		generator: {language: "java", sdk: "docuconf-spring", version: "VERSION"}
	}
	vars: {
		GATEWAY_ADMIN_APIKEY: {
			type: "string"
			description: "Key that authorizes calls to the admin API."
			required: true
			secret: true
			group: "admin"
			configKey: "gateway.admin.api-key"
			minLength: 1
			pattern: "\\S"
		}
		GATEWAY_ALLOWEDORIGINS: {
			type: "list"
			description: "Origins allowed to call the gateway from a browser."
			group: "http"
			configKey: "gateway.allowed-origins"
			examples: ["https://app.example.com,https://admin.example.com"]
			items: "string"
			encoding: "csv"
			maxItems: 10
			default: ["https://app.example.com"]
		}
		GATEWAY_COMPRESSION: {
			type: "bool"
			description: "Whether to compress responses."
			group: "http"
			configKey: "gateway.compression"
			default: true
		}
		GATEWAY_FILES_PARTNERKEYSTOREPASSWORD: {
			type: "string"
			description: "Password for the partner mTLS keystore"
			required: true
			secret: true
			configKey: "gateway.files.partner-keystore-password"
		}
		GATEWAY_LOGLEVEL: {
			type: "enum"
			description: "Minimum log level emitted."
			configKey: "gateway.log-level"
			values: ["DEBUG", "INFO", "WARN", "ERROR"]
			default: "INFO"
		}
		GATEWAY_PODNAMESPACE: {
			type: "string"
			description: "Namespace the gateway runs in, for metrics labels."
			required: true
			configKey: "gateway.pod-namespace"
			minLength: 1
			pattern: "\\S"
		}
		GATEWAY_PORT: {
			type: "int"
			description: "HTTPS listen port."
			group: "http"
			configKey: "gateway.port"
			min: 1
			max: 65535
			default: 8443
		}
		GATEWAY_PROBEPORTS: {
			type: "list"
			description: "Ports the health checker probes on each upstream."
			configKey: "gateway.probe-ports"
			items: "int"
			encoding: "csv"
			default: [8080, 9090]
		}
		GATEWAY_RATELIMITS: {
			type: "json"
			description: "Default per-client rate limits."
			required: true
			configKey: "gateway.rate-limits"
			schema: {
				"type": "object"
				"description": "Per-client rate limits."
				"properties": {
					"perMinute": {
						"type": "integer"
						"description": "Requests allowed per minute"
						"minimum": 1
					}
					"burst": {
						"type": "integer"
						"description": "Extra requests allowed in a burst"
						"minimum": 0
					}
				}
				"additionalProperties": false
			}
		}
		GATEWAY_REGION: {
			type: "string"
			description: "Cloud region the gateway runs in, such as eu-west-1."
			configKey: "gateway.region"
			pattern: "^(?:[a-z]{2}-[a-z]+-[0-9])$"
			default: "eu-west-1"
		}
		GATEWAY_SESSIONSTOREURL: {
			type: "url"
			description: "Session store connection string."
			required: true
			secret: true
			configKey: "gateway.session-store-url"
			schemes: ["redis", "rediss"]
		}
		GATEWAY_TRACESAMPLING: {
			type: "float"
			description: "Fraction of requests to trace, from 0 to 1."
			configKey: "gateway.trace-sampling"
			min: 0
			max: 1
			default: 0.1
		}
		GATEWAY_UPSTREAMTIMEOUT: {
			type: "duration"
			description: "Upstream request timeout."
			group: "http"
			configKey: "gateway.upstream-timeout"
			encoding: "iso8601"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		SPRING_PROFILES_ACTIVE: {
			type: "string"
			description: "Active Spring profile; selects the application-{profile}.yml baked into the image"
			configKey: "spring.profiles.active"
			pattern: "^[^,]+$"
			default: "default"
		}
	}
	files: {
		geoip: {
			type: "binary"
			description: "GeoIP database for country-based routing"
			path: "/data/geoip/GeoLite2-City.mmdb"
			maxSize: 134217728
		}
		license: {
			type: "text"
			description: "Gateway licence key"
			required: true
			path: "/etc/gateway/license/license.key"
			pattern: "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type: "keystore"
			format: "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			secret: true
			path: "/etc/gateway/partner/keystore.p12"
			passwordVar: "GATEWAY_FILES_PARTNERKEYSTOREPASSWORD"
		}
		routes: {
			type: "config"
			format: "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required: true
			path: "/etc/gateway/routes/routes.yaml"
			pathEnv: "ROUTES_FILE"
			reload: "watch"
			maxSize: 65536
			schema: {
				"type": "object"
				"description": "The routing table."
				"properties": {
					"routes": {
						"type": "array"
						"items": {
							"type": "object"
							"description": "One route."
							"properties": {
								"match": {
									"type": "string"
									"description": "Path prefix to match"
									"minLength": 1
									"pattern": "^(?:/.*)$"
								}
								"upstream": {
									"type": "string"
									"format": "uri"
									"description": "Upstream base URL"
								}
								"timeout": {
									"type": ["string", "number"]
									"description": "Per-route timeout, overriding the gateway default"
								}
							}
							"additionalProperties": false
							"required": ["match", "upstream"]
						}
						"description": "Routes, matched in order"
						"minItems": 1
					}
				}
				"additionalProperties": false
				"required": ["routes"]
			}
		}
		"serving-tls": {
			type: "tls"
			description: "Certificate the gateway serves HTTPS with"
			required: true
			secret: true
			path: "/etc/gateway/tls"
			reload: "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
		"upstream-ca": {
			type: "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path: "/etc/gateway/ca/bundle.pem"
			pathEnv: "SSL_CERT_FILE"
		}
	}
	profiles: {
		selector: "SPRING_PROFILES_ACTIVE"
		default: "default"
		defaults: {
			dev: {
				GATEWAY_COMPRESSION: false
				GATEWAY_LOGLEVEL: "DEBUG"
			}
			prod: {
				GATEWAY_LOGLEVEL: "WARN"
				GATEWAY_TRACESAMPLING: 0.01
			}
		}
	}
}
