package dev.docuconf.contract;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Writes a contract as plain CUE data unified with {@code contract.#Contract} (SPEC §4). Output is deterministic:
 * variables, file inputs and profiles are sorted by name, and fields come in a fixed order.
 */
public final class CueWriter {

    private static final Pattern IDENT = Pattern.compile("^[A-Za-z][A-Za-z0-9_]*$");
    private static final Set<String> KEYWORDS = Set.of(
            "package", "import", "for", "in", "if", "let", "true", "false", "null", "div", "mod", "quo", "rem", "func");

    private final StringBuilder b = new StringBuilder();
    private int depth;

    private CueWriter() {
    }

    /**
     * Writes a contract.
     *
     * @param c the contract
     * @return the CUE document
     */
    public static String write(Contract c) {
        return new CueWriter().contract(c);
    }

    /**
     * The CUE package name for a service: lower-case letters, digits and underscores.
     *
     * @param service the service name
     * @return the package name
     */
    public static String packageName(String service) {
        String p = service.toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9_]", "_");
        if (p.isEmpty() || !Character.isLetter(p.charAt(0))) {
            p = "svc_" + p;
        }
        return KEYWORDS.contains(p) ? p + "_contract" : p;
    }

    private String contract(Contract c) {
        b.append("// Code generated by docuconf. DO NOT EDIT.\n");
        b.append("package ").append(packageName(c.name)).append("\n\n");
        b.append("import \"docuconf.dev/contract\"\n\n");
        b.append("contract.#Contract & {\n");
        depth = 1;
        field("apiVersion", "docuconf.dev/v1alpha1");
        field("kind", "ConfigContract");
        open("metadata");
        field("name", c.name);
        if (c.appVersion != null) {
            field("appVersion", c.appVersion);
        }
        line("generator: {language: " + str(Contract.LANGUAGE) + ", sdk: " + str(c.sdk) + ", version: "
                + str(c.sdkVersion) + "}");
        close();
        open("vars");
        for (VarSpec v : c.vars.values()) {
            var(v);
        }
        close();
        if (!c.files.isEmpty()) {
            open("files");
            for (FileSpec f : c.files.values()) {
                file(f);
            }
            close();
        }
        if (!c.overlays.isEmpty()) {
            open("overlays");
            for (OverlaySpec o : c.overlays.values()) {
                open(label(o.name));
                opt("description", o.description);
                field("format", o.format);
                field("path", o.path);
                field("keySeparator", o.keySeparator);
                if (!"restart".equals(o.reload)) {
                    field("reload", o.reload);
                }
                close();
            }
            close();
        }
        if (c.profiles != null) {
            open("profiles");
            field("selector", c.profiles.selector);
            field("default", c.profiles.defaultProfile);
            open("defaults");
            for (Map.Entry<String, Map<String, Object>> p : c.profiles.defaults.entrySet()) {
                open(label(p.getKey()));
                for (Map.Entry<String, Object> e : p.getValue().entrySet()) {
                    value(label(e.getKey()), e.getValue());
                }
                close();
            }
            close();
            close();
        }
        b.append("}\n");
        return b.toString();
    }

    private void var(VarSpec v) {
        open(label(v.name));
        field("type", v.type.id());
        field("description", v.description);
        if (v.details != null) {
            field("details", v.details);
        }
        if (v.required) {
            line("required: true");
        }
        if (v.secret) {
            line("secret: true");
        }
        if (v.group != null) {
            field("group", v.group);
        }
        if (v.configKey != null) {
            field("configKey", v.configKey);
        }
        if (v.examples != null && !v.examples.isEmpty()) {
            value("examples", v.examples);
        }
        deprecated(v.deprecated);
        switch (v.type) {
            case STRING -> {
                opt("minLength", v.minLength);
                opt("maxLength", v.maxLength);
                opt("pattern", v.pattern);
            }
            case INT, FLOAT -> {
                opt("min", v.min);
                opt("max", v.max);
            }
            case DURATION -> {
                opt("encoding", v.encoding);
                opt("min", v.min);
                opt("max", v.max);
            }
            case URL -> {
                opt("schemes", v.schemes);
                opt("maxLength", v.maxLength);
            }
            case ENUM -> value("values", v.values);
            case LIST -> {
                field("items", v.items);
                opt("encoding", v.encoding);
                if (v.separator != null && !v.separator.equals(",")) {
                    field("separator", v.separator);
                }
                opt("minItems", v.minItems);
                opt("maxItems", v.maxItems);
                opt("itemMin", v.itemMin);
                opt("itemMax", v.itemMax);
                opt("itemMinLength", v.itemMinLength);
                opt("itemMaxLength", v.itemMaxLength);
            }
            case JSON -> {
                opt("maxLength", v.maxLength);
                opt("schema", v.schema);
            }
            default -> {
            }
        }
        opt("default", v.defaultValue);
        close();
    }

    private void file(FileSpec f) {
        open(label(f.name));
        field("type", f.type.id());
        if (f.format != null) {
            field("format", f.format);
        }
        field("description", f.description);
        if (f.details != null) {
            field("details", f.details);
        }
        if (f.required) {
            line("required: true");
        }
        if (f.secret) {
            line("secret: true");
        }
        if (f.group != null) {
            field("group", f.group);
        }
        field("path", f.path);
        opt("pathEnv", f.pathEnv);
        if (!"restart".equals(f.reload)) {
            field("reload", f.reload);
        }
        opt("maxSize", f.maxSize);
        deprecated(f.deprecated);
        switch (f.type) {
            case CONFIG -> opt("schema", f.schema);
            case TLS -> {
                opt("dnsNames", f.dnsNames);
                opt("keyAlgorithms", f.keyAlgorithms);
                opt("minRemaining", f.minRemaining);
                if (f.requireCA) {
                    line("requireCA: true");
                }
            }
            case CA_BUNDLE -> {
                if (f.minCertificates != null && f.minCertificates != 1) {
                    opt("minCertificates", f.minCertificates);
                }
            }
            case KEYSTORE -> opt("passwordVar", f.passwordVar);
            case TEXT -> {
                opt("pattern", f.pattern);
                opt("minLength", f.minLength);
                opt("maxLength", f.maxLength);
            }
            default -> {
            }
        }
        close();
    }

    private void deprecated(Deprecation d) {
        if (d == null) {
            return;
        }
        String s = "deprecated: {message: " + str(d.message());
        if (d.replacedBy() != null) {
            s += ", replacedBy: " + str(d.replacedBy());
        }
        line(s + "}");
    }

    private void opt(String key, Object v) {
        if (v == null || (v instanceof List<?> l && l.isEmpty())) {
            return;
        }
        value(key, v);
    }

    private void field(String key, String v) {
        line(key + ": " + str(v));
    }

    private void value(String key, Object v) {
        indent();
        b.append(key).append(": ");
        literal(v);
        b.append('\n');
    }

    /** Lists of scalars go on one line; structs and lists of structs are expanded. */
    private void literal(Object v) {
        if (v instanceof Map<?, ?> m) {
            if (m.isEmpty()) {
                b.append("{}");
                return;
            }
            b.append("{\n");
            depth++;
            for (Map.Entry<?, ?> e : m.entrySet()) {
                indent();
                b.append(str(String.valueOf(e.getKey()))).append(": ");
                literal(e.getValue());
                b.append('\n');
            }
            depth--;
            indent();
            b.append('}');
        } else if (v instanceof List<?> l) {
            boolean scalars = l.stream().noneMatch(o -> o instanceof Map || o instanceof List);
            if (scalars) {
                b.append('[');
                for (int k = 0; k < l.size(); k++) {
                    if (k > 0) {
                        b.append(", ");
                    }
                    literal(l.get(k));
                }
                b.append(']');
                return;
            }
            b.append("[\n");
            depth++;
            for (Object o : l) {
                indent();
                literal(o);
                b.append(",\n");
            }
            depth--;
            indent();
            b.append(']');
        } else if (v instanceof String s) {
            b.append(str(s));
        } else if (v instanceof BigDecimal d) {
            b.append(Json.number(d));
        } else if (v == null) {
            b.append("null");
        } else if (v instanceof Double || v instanceof Float) {
            b.append(Json.number(new BigDecimal(v.toString())));
        } else {
            b.append(v);
        }
    }

    private void open(String key) {
        line(key + ": {");
        depth++;
    }

    private void close() {
        depth--;
        line("}");
    }

    private void line(String s) {
        indent();
        b.append(s).append('\n');
    }

    private void indent() {
        b.append("\t".repeat(depth));
    }

    private static String str(String s) {
        StringBuilder q = new StringBuilder();
        Json.quote(q, s);
        return q.toString();
    }

    private static String label(String key) {
        return IDENT.matcher(key).matches() && !KEYWORDS.contains(key) ? key : str(key);
    }
}
